/* ==========================================================================
   SITE DATA
   Everything the site renders lives here. Edit this file to update content.
   - `skills[].links` attaches each skill to the project(s) / roles that use it.
     Ids must match a project `id` or an experience `id` below.
   ========================================================================== */

window.SITE = {
  profile: {
    name: "Saideep Katragadda",
    first: "Saideep",
    last: "Katragadda",
    roles: [
      "Software Engineer",
      "Machine Learning Builder",
      "Quantitative Developer",
      "Undergraduate Researcher",
      "Data Scientist",
    ],
    intro:
      "Computer Science student at Texas A&M building full-stack analytics platforms, machine learning systems, and AI automation — from NBA Monte Carlo simulations to airline demand forecasting.",
    location: "College Station, TX",
    phone: "512-648-7227",
    email: "sdkatragadda@gmail.com",
    linkedin: "https://www.linkedin.com/in/saideep-katragadda-85907a2ba",
    linkedinLabel: "linkedin.com/in/saideep-katragadda",
    github: "https://github.com/sydip",
    githubLabel: "github.com/sydip",
    resume: "assets/Saideep_Katragadda_Resume.pdf",
    // the About tab's opening paragraph
    about:
      "I'm a Computer Science student at Texas A&amp;M University, building software for full-stack engineering and machine learning. Right now I'm leading a team forecasting airline demand for American Airlines, researching exoskeleton adoption, and building ML trading models. I also love sports, which drives my NBA and NFL analytics projects.",
    // typed (and deleted) one after another on the home screen, after "Building as a"
    buildingAs: ["Software Engineer", "Machine Learning Engineer", "Full-Stack Developer"],
  },

  education: {
    school: "Texas A&M University",
    degree: "Bachelor of Science in Computer Science",
    location: "College Station, TX",
    dates: "Aug 2025 – May 2028 (expected)",
    organizations: ["Aggie Data Science Club (ADSC)", "Maroon Investment Club"],
    coursework: [
      { code: "ENGR 102", name: "Python Computation" },
      { code: "ISTM 209", name: "Information Systems Concepts" },
      { code: "CSCE 222", name: "Discrete Structures" },
      { code: "CSCE 120", name: "Program Design and Concepts" },
      { code: "CSCE 221", name: "Data Structures and Algorithms" },
      { code: "STAT 211", name: "Principles of Statistics" },
      { code: "CSCE 314", name: "Programming Languages" },
      { code: "MATH 304", name: "Linear Algebra" },
    ],
    certifications: [
      "IT Specialist – Java (Certiport)",
      "Microsoft Office Specialist – Word, Excel, PowerPoint, Access",
    ],
  },

  experience: [
    {
      id: "american-airlines",
      role: "Software Engineer Team Lead",
      org: "American Airlines × ADSC",
      location: "College Station, TX",
      dates: "Oct 2026 – Present",
      current: true,
      summary: "Leading a team forecasting airline market demand for Network Planning.",
      bullets: [
        "Leading a <b>team of 6</b> working with <b>American Airlines</b> to predict how many people will want to fly to different places <b>up to two years ahead</b>, to help the airline's route-planning team.",
        "Guiding the team on which factors, like regional and population trends, drive travel demand, and checking our predictions against what actually happened in past years.",
      ],
    },
    {
      id: "research",
      role: "Undergraduate Researcher",
      org: "Texas A&M University",
      location: "College Station, TX",
      dates: "Oct 2026 – Present",
      current: true,
      summary: "Agent-based modeling of exoskeleton adoption in construction.",
      bullets: [
        "Building a <b>computer simulation</b> of how construction workers and crews decide whether to start, and keep, using <b>wearable exoskeletons</b>: assistive suits that reduce physical strain on the job.",
        "Basing the simulation on published studies and expert input, then testing it to find <b>what makes workers stick with the technology</b> or give it up.",
      ],
    },
    {
      id: "ufcu",
      role: "Application Developer Intern",
      org: "University Federal Credit Union (UFCU)",
      location: "Austin, TX",
      dates: "Jun 2026 – Aug 2026",
      current: false,
      summary: "AI automation agents and meeting intelligence inside Azure DevOps.",
      bullets: [
        "Built <b>AI assistants</b> that took over routine project-management work for software teams, and a tool that turned <b>Microsoft Teams meetings</b> into written summaries of decisions and next steps.",
        "Fixed an issue that was causing some <b>loan requests to fail</b>, and automated manual project-tracking work to save the team time and keep records accurate.",
      ],
    },
    {
      id: "maroon",
      role: "Quantitative Developer",
      org: "Maroon Investment Club",
      location: "College Station, TX",
      dates: "Mar 2026 – Present",
      current: true,
      summary: "ML trading signals during market dislocations.",
      bullets: [
        "Built a <b>machine-learning tool</b> that spots good moments to buy and sell stocks when the market swings sharply, designed to keep working on new data, not just the history it learned from.",
        "Tested on past market data, it earned a <b>36% return</b>, compared with <b>14% for the S&amp;P 500</b>.",
      ],
    },
  ],

  projects: [
    {
      id: "courtvision",
      github: "https://github.com/sydip/CourtVision",
      name: "CourtVision",
      kicker: "NBA Analytics Platform",
      dates: "Jun 2026 – Aug 2026",
      tagline: "Full-stack NBA analytics with a random-forest prediction engine and Monte Carlo playoff simulation.",
      stack: ["Python", "JavaScript", "TypeScript", "PostgreSQL", "FastAPI", "Next.js", "Docker"],
      stats: [
        { value: 131000, suffix: "+", label: "Player game logs" },
        { value: 6151, label: "Games ingested" },
        { value: 19, label: "Random-forest models" },
        { value: 10000, label: "Monte Carlo runs" },
        { value: 80, suffix: "%", label: "MVP/ROY top-3 hit rate" },
        { value: 95, suffix: "%", label: "AI query routing" },
      ],
      bullets: [
        "Built a full-stack NBA analytics platform (FastAPI, PostgreSQL, Next.js) ingesting <b>131,000+ player game logs</b> across <b>6,151 games</b> and <b>26 draft classes</b>, with raw-cached, validated, and resumable data pipelines.",
        "Developed a <b>random-forest prediction engine with 19 models</b> and a <b>10,000-run Monte Carlo</b> Finals simulation, ranking the actual MVP and Rookie of the Year in the top 3 in <b>80% of backtested seasons</b>.",
        "Reached <b>94+% player similarity modeling accuracy</b>, powering an AI basketball assistant with <b>95% query-routing accuracy</b> that turns statistical output into natural-language insights.",
        "Delivered 10+ analytics features: performance trends, matchup splits, player comparisons, playoff analysis, draft evaluation, and roster tracking.",
      ],
    },
    {
      id: "senna",
      github: "", // paste the repo URL here
      name: "Senna",
      kicker: "Formula 1 Telemetry Platform",
      dates: "Jul 2026 – Aug 2026",
      tagline: "Telemetry pipelines, tire-degradation forecasting, and an AI race engineer.",
      stack: ["React", "TypeScript", "Python", "FastAPI", "Tailwind CSS"],
      stats: [
        { value: 93, suffix: "%", label: "Tire deg & lap pace accuracy" },
        { value: 5, label: "Telemetry channels modeled" },
        { text: "AI", label: "Race-engineer coaching" },
      ],
      bullets: [
        "Designed a <b>Formula 1 analytics platform</b> that processes per-race telemetry to power interactive driver-performance and race-comparison dashboards.",
        "Engineered <b>telemetry pipelines</b> and a predictive ML model using braking, throttle, speed, gear, and cornering data to forecast <b>tire degradation and lap pace with 93% accuracy</b>.",
        "Integrated an <b>AI-powered race engineer</b> that converts validated telemetry into coaching insights, performance summaries, and race-strategy recommendations through scalable backend APIs.",
      ],
    },
    {
      id: "gridiron",
      github: "https://github.com/sydip/Gridiron",
      name: "Gridiron",
      kicker: "NFL Against-the-Spread Analytics",
      dates: "Aug 2026 – Sep 2026",
      tagline: "Leakage-safe NFL ATS modeling with walk-forward validation and a 737-test suite.",
      stack: ["Python", "Pandas", "Scikit-Learn", "Seaborn", "FastAPI", "React", "TypeScript"],
      stats: [
        { value: 489000, suffix: "+", label: "Plays ingested" },
        { value: 2911, label: "Games" },
        { value: 737, label: "Tests" },
        { value: 11, label: "Engineered features" },
        { value: 1828, label: "Out-of-sample games" },
        { value: 181, label: "Team-games recovered" },
      ],
      bullets: [
        "Engineered a full-stack NFL against-the-spread analytics platform ingesting <b>489,000+ plays</b> across <b>2,911 games</b> with validated, idempotent pipelines and a <b>737-test suite</b> guaranteeing byte-identical served data.",
        "Developed a <b>leakage-safe logistic-regression model</b> with <b>11 engineered features</b> (rolling offensive/defensive EPA, pace, rest, recent form, betting lines), validated via <b>7-fold walk-forward</b> testing on <b>1,828 out-of-sample games</b>.",
        "Caught a silent data-join fault that had dropped <b>181 team-games</b> of EPA and pace data, and generated weekly matchup probabilities, confidence rankings, backtests, and seaborn reports.",
      ],
    },
    {
      id: "pixel-pathology",
      github: "https://github.com/TAMU-Aggie-Data-Science-Club/fall2026-pixel-pathology",
      name: "Pixel Pathology",
      kicker: "Interpretable Medical Imaging · ADSC",
      dates: "Sep 2026 – Present",
      tagline: "A CNN medical image classifier that shows its work with Grad-CAM heatmaps.",
      stack: ["Python", "PyTorch", "TensorFlow", "CNNs", "Git/GitHub"],
      stats: [
        { text: "CNN", label: "Transfer-learned classifier" },
        { text: "Grad-CAM", label: "Explainability" },
        { text: "Transfer", label: "Learning strategy" },
      ],
      bullets: [
        "Building an interpretable <b>CNN medical image classifier</b> in <b>PyTorch</b> using <b>transfer learning</b> and <b>data augmentation</b>.",
        "Generating <b>Grad-CAM heatmaps</b> that highlight the image regions driving each prediction, so model decisions can be inspected.",
        "Handling image preprocessing and augmentation, with <b>GitHub-based collaborative</b> model development across the ADSC team.",
      ],
    },
    {
      id: "cosmos",
      github: "https://github.com/Pri1s/cosmos",
      name: "Cosmos",
      kicker: "NASA Knowledge Graph",
      dates: "Mar 2026",
      tagline: "An interactive spiral-galaxy knowledge graph of NASA exoplanets and missions, with an AI guide.",
      stack: ["React", "Vite", "D3.js", "JavaScript", "HTML/CSS"],
      stats: [
        { value: 60, label: "FPS rendering" },
        { text: "WebGL", label: "Canvas renderer" },
        { text: "Stella", label: "AI guide" },
      ],
      bullets: [
        "Developed an interactive knowledge-graph platform using <b>React, Vite, and D3 force simulations</b> to visualize NASA exoplanet and mission data in a dynamic spiral-galaxy layout.",
        "Implemented <b>WebGL-accelerated canvas rendering</b> with react-force-graph-2d for force-directed nodes, animated star fields, and mission relationships at a smooth <b>60 FPS</b>.",
        "Created <b>“Stella,”</b> an AI conversational guide with session memory that answers natural-language questions about exoplanets and NASA missions.",
        "Engineered custom graph physics and coordinate mapping to balance galaxy aesthetics, collision resolution, and detail-panel positioning during real-time pan and zoom.",
      ],
    },
    {
      id: "portfolio",
      github: "https://github.com/sydip/SaideepKatragadda",
      name: "Portfolio",
      kicker: "Interactive Portfolio Website",
      dates: "Oct 2026",
      tagline: "This site: a low-poly wireframe head, a clickable skills brain and tabbed pages, built from scratch with HTML, CSS and canvas.",
      stack: ["JavaScript", "HTML/CSS", "Canvas 2D", "GitHub Pages"],
      stats: [
        { value: 34, label: "Skills mapped in an interactive brain" },
        { value: 6, label: "Projects with full write-ups" },
      ],
      bullets: [
        "Built a single-page portfolio in <b>vanilla JavaScript, HTML and CSS</b> with no framework or build step, deployed on <b>GitHub Pages</b>.",
        "Procedurally generated a <b>low-poly wireframe head</b> and a <b>clickable brain</b> of skills (Delaunay triangulation), rendered on <b>Canvas 2D</b> at 60 FPS.",
        "Drew an animated <b>circuit-trace background</b> behind every tab, cut away wherever the head's mesh sits.",
      ],
    },
  ],

  /* Skills tab: the brain's six regions, one per category. Everything in the resume's Technical Skills
     section (except the certifications), plus the skills that come up across several projects or roles and the ones a project is
     built on (XGBoost, D3.js…). */
  skillBrain: [
    { id: "ml", name: "Machine Learning & AI", region: "Frontal lobe", note: "reasoning and prediction",
      skills: ["Scikit-Learn", "PyTorch / TensorFlow", "XGBoost", "Time-Series Forecasting", "Walk-Forward Validation", "LLM APIs (Claude / Gemini)"] },
    { id: "languages", name: "Languages", region: "Parietal lobe", note: "language and symbols",
      skills: ["Python", "Java", "C++", "TypeScript", "JavaScript", "SQL", "HTML/CSS"] },
    { id: "frontend", name: "Frontend", region: "Occipital lobe", note: "vision",
      skills: ["React", "Next.js", "Tailwind CSS", "D3.js", "Recharts", "Vite"] },
    { id: "data", name: "Data & Simulation", region: "Temporal lobe", note: "memory",
      skills: ["Pandas", "NumPy", "Seaborn", "Monte Carlo Simulation", "Agent-Based Modeling (NetLogo)"] },
    { id: "tools", name: "Tools & Testing", region: "Cerebellum", note: "coordination",
      skills: ["Git / GitHub", "Azure DevOps", "pytest", "Vitest", "VS Code", "Eclipse"] },
    { id: "backend", name: "Backend", region: "Brainstem", note: "the backbone everything runs through",
      skills: ["FastAPI", "PostgreSQL", "Docker", "Postman"] },
  ],

  /* Skills section: how the skills are grouped around the hologram head.
     A skill can sit in more than one domain; any skill left out lands in "Other". */
  skillDomains: [
    { id: "ml", name: "Machine Learning & AI", icon: "brain", blurb: "Models that learn, forecast and explain themselves.",
      skills: ["PyTorch / TensorFlow", "CNNs & Transfer Learning", "Scikit-Learn", "XGBoost", "Time-Series Forecasting", "Walk-Forward Validation", "LLM APIs (Claude / Gemini)", "joblib"] },
    { id: "data", name: "Data Science & Analytics", icon: "chart", blurb: "Cleaning, modeling and simulating real-world data.",
      skills: ["Python", "Pandas", "NumPy", "SQL", "Matplotlib", "Seaborn", "Monte Carlo Simulation", "Agent-Based Modeling (NetLogo)", "Plotly"] },
    { id: "backend", name: "Backend", icon: "server", blurb: "APIs, data pipelines and the databases behind them.",
      skills: ["Python", "FastAPI", "Pydantic", "SQLAlchemy / Alembic", "PostgreSQL", "SQL", "Java", "C++"] },
    { id: "frontend", name: "Frontend", icon: "window", blurb: "Interactive interfaces and data visualization.",
      skills: ["JavaScript", "TypeScript", "React", "HTML/CSS", "Tailwind CSS", "D3.js", "Recharts", "Plotly", "TanStack Query", "Zustand", "Vite"] },
    { id: "fullstack", name: "Full Stack", icon: "layers", blurb: "End-to-end apps, from the database to the browser.",
      skills: ["Next.js", "React", "TypeScript", "FastAPI", "PostgreSQL", "OpenAPI / openapi-typescript", "TanStack Query", "Docker"] },
    { id: "devops", name: "DevOps & Tooling", icon: "terminal", blurb: "Shipping, testing and collaborating on code.",
      skills: ["Git / GitHub", "Docker", "Azure DevOps", "Postman", "VS Code", "Eclipse"] },
    { id: "testing", name: "Testing & Quality", icon: "check", blurb: "Tests, types and linting that keep code honest.",
      skills: ["pytest", "Hypothesis", "Vitest", "Testing Library", "Playwright", "Load Testing (k6 / Locust)", "mypy", "Ruff", "ESLint", "Prettier"] },
  ],

  /* Skill → where it's used. Add / refine freely; links can point at project ids or experience ids. */
  skillCategories: ["Languages", "Frameworks & Libraries", "ML & Data", "Tools & Infrastructure"],
  skills: [
    { name: "Python", cat: "Languages", links: ["courtvision", "senna", "gridiron", "pixel-pathology", "maroon", "research"] },
    { name: "TypeScript", cat: "Languages", links: ["courtvision", "senna", "gridiron"] },
    { name: "JavaScript", cat: "Languages", links: ["courtvision", "cosmos", "portfolio"] },
    { name: "SQL", cat: "Languages", links: ["courtvision"] },
    { name: "HTML/CSS", cat: "Languages", links: ["cosmos", "portfolio"] },
    { name: "Java", cat: "Languages", links: [], note: "Certiport IT Specialist – Java" },
    { name: "C++", cat: "Languages", links: [], note: "CSCE 120 · Program Design and Concepts" },

    { name: "React", cat: "Frameworks & Libraries", links: ["courtvision", "senna", "gridiron", "cosmos"] },
    { name: "Next.js", cat: "Frameworks & Libraries", links: ["courtvision"] },
    { name: "FastAPI", cat: "Frameworks & Libraries", links: ["courtvision", "senna", "gridiron"] },
    { name: "Tailwind CSS", cat: "Frameworks & Libraries", links: ["courtvision", "senna", "gridiron"] },
    { name: "Pydantic", cat: "Frameworks & Libraries", links: ["courtvision"] },
    { name: "D3.js", cat: "Frameworks & Libraries", links: ["cosmos"] },
    { name: "Recharts", cat: "Frameworks & Libraries", links: ["courtvision", "gridiron"] },
    { name: "SQLAlchemy / Alembic", cat: "Frameworks & Libraries", links: ["courtvision"] },
    { name: "Vite", cat: "Frameworks & Libraries", links: ["cosmos", "gridiron"] },
    { name: "Plotly", cat: "Frameworks & Libraries", links: [] },
    { name: "TanStack Query", cat: "Frameworks & Libraries", links: ["courtvision"] },
    { name: "Zustand", cat: "Frameworks & Libraries", links: [] },
    { name: "OpenAPI / openapi-typescript", cat: "Frameworks & Libraries", links: [] },

    { name: "PyTorch / TensorFlow", cat: "ML & Data", links: ["pixel-pathology"] },
    { name: "CNNs & Transfer Learning", cat: "ML & Data", links: ["pixel-pathology"] },
    { name: "Scikit-Learn", cat: "ML & Data", links: ["courtvision", "gridiron"] },
    { name: "NumPy", cat: "ML & Data", links: ["courtvision", "gridiron"] },
    { name: "joblib", cat: "ML & Data", links: ["courtvision", "gridiron"] },
    { name: "XGBoost", cat: "ML & Data", links: ["maroon"] },
    { name: "Pandas", cat: "ML & Data", links: ["gridiron", "courtvision", "american-airlines"] },
    { name: "Matplotlib", cat: "ML & Data", links: ["gridiron"] },
    { name: "Seaborn", cat: "ML & Data", links: ["gridiron"] },
    { name: "LLM APIs (Claude / Gemini)", cat: "ML & Data", links: ["courtvision", "cosmos"] },
    { name: "Monte Carlo Simulation", cat: "ML & Data", links: ["courtvision"] },
    { name: "Time-Series Forecasting", cat: "ML & Data", links: ["american-airlines", "senna"] },
    { name: "Walk-Forward Validation", cat: "ML & Data", links: ["gridiron", "maroon"] },
    { name: "Agent-Based Modeling (NetLogo)", cat: "ML & Data", links: ["research"] },

    { name: "PostgreSQL", cat: "Tools & Infrastructure", links: ["courtvision"] },
    { name: "Docker", cat: "Tools & Infrastructure", links: ["courtvision"] },
    { name: "Git / GitHub", cat: "Tools & Infrastructure", links: ["pixel-pathology", "gridiron", "courtvision", "portfolio"] },
    { name: "Azure DevOps", cat: "Tools & Infrastructure", links: ["ufcu"] },
    { name: "Postman", cat: "Tools & Infrastructure", links: ["ufcu"] },
    { name: "pytest", cat: "Tools & Infrastructure", links: ["courtvision", "gridiron"] },
    { name: "Vitest", cat: "Tools & Infrastructure", links: ["courtvision", "cosmos"] },
    { name: "Prettier", cat: "Tools & Infrastructure", links: ["courtvision"] },
    { name: "ESLint", cat: "Tools & Infrastructure", links: ["courtvision", "cosmos"] },
    { name: "Ruff", cat: "Tools & Infrastructure", links: ["courtvision", "gridiron"] },
    { name: "mypy", cat: "Tools & Infrastructure", links: ["courtvision"] },
    { name: "Hypothesis", cat: "Tools & Infrastructure", links: [] },
    { name: "Testing Library", cat: "Tools & Infrastructure", links: ["courtvision"] },
    { name: "Playwright", cat: "Tools & Infrastructure", links: ["courtvision"] },
    { name: "Load Testing (k6 / Locust)", cat: "Tools & Infrastructure", links: [] },
    { name: "VS Code", cat: "Tools & Infrastructure", links: [] },
    { name: "Eclipse", cat: "Tools & Infrastructure", links: [] },
  ],
};
